services:
  dastardly-daemon:
    build: .
    image: cyclefive/dastardly-daemon:dev
    container_name: dastardly-daemon
    restart: unless-stopped
    secrets:
      - DISCORD_TOKEN
    environment:
      - RUST_LOG=info,serenity=error
      - DISCORD_TOKEN_FILE=/run/secrets/DISCORD_TOKEN
    volumes:
      - daemon_app_data:/app/data
      - daemon_app_logs:/app/logs
secrets:
  DISCORD_TOKEN:
    file: ./discord_token.txt
volumes:
  daemon_app_data:
    external: true
    #driver: local
  daemon_app_logs:
    external: true
    #driver: local
